### ISSUE TITLE
bundled versioneer 0.18 is incompatible with Python 3.12

### ISSUE THREAD

**Issue by rathann** [MDAnalysis/GridDataFormats#124]
This leads to an error:
```
$ /usr/bin/python3 setup.py build '--executable=/usr/bin/python3 -sP'
/builddir/build/BUILD/GridDataFormats-1.0.1/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
  LONG_VERSION_PY['git'] = '''
Traceback (most recent call last):
  File "/builddir/build/BUILD/GridDataFormats-1.0.1/setup.py", line 13, in <module>
    version=versioneer.get_version(),
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/GridDataFormats-1.0.1/versioneer.py", line 1480, in get_version
    return get_versions()["version"]
           ^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/GridDataFormats-1.0.1/versioneer.py", line 1412, in get_versions
    cfg = get_config_from_root(root)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/GridDataFormats-1.0.1/versioneer.py", line 342, in get_config_from_root
    parser = configparser.SafeConfigParser()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
```

Please either unbundle or update to the latest 0.28 version, which seems to work fine.

**Comment by orbeckst** [comment]
Fixed in PR #128
