### ISSUE TITLE
gridData.tests.test_dx.test_write_dx_ValueError fails on ARM 32-bit

### ISSUE THREAD

**Issue by rathann** [MDAnalysis/GridDataFormats#51]
When running 0.4.0 tests (with 605a20fa7f8e9b880d26e9783f62ee3d03fc0797 applied) on Fedora rawhide on armv7hl (ARM 32-bit), `gridData.tests.test_dx.test_write_dx_ValueError` test fails:
```
$ cd GridDataFormats-0.4.0
$ /usr/bin/python2 setup.py nosetests
running nosetests
running egg_info
writing requirements to GridDataFormats.egg-info/requires.txt
writing GridDataFormats.egg-info/PKG-INFO
writing top-level names to GridDataFormats.egg-info/top_level.txt
writing dependency_links to GridDataFormats.egg-info/dependency_links.txt
reading manifest file 'GridDataFormats.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'README'
writing manifest file 'GridDataFormats.egg-info/SOURCES.txt'
.............F............S..
======================================================================
FAIL: gridData.tests.test_dx.test_write_dx_ValueError
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/lib/python2.7/site-packages/nose/tools/nontrivial.py", line 60, in newfunc
    func(*arg, **kw)
  File "/builddir/build/BUILD/GridDataFormats-0.4.0/gridData/tests/test_dx.py", line 89, in test_write_dx_ValueError
    return _test_write_dx(nptype=nptype, dxtype=dxtype)
  File "/builddir/build/BUILD/GridDataFormats-0.4.0/gridData/tests/test_dx.py", line 48, in _test_write_dx
    assert_equal(out_dxtype, dxtype)
  File "/usr/lib/python2.7/site-packages/numpy/testing/nose_tools/utils.py", line 411, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: 'double'
 DESIRED: 'unknown'
----------------------------------------------------------------------
Ran 29 tests in 1.106s
FAILED (SKIP=1, failures=1)
```

I suspect it's due to some change in numpy.

**Comment by rathann** [comment]
It looks like `np.longdouble` and `np.double` are different on x86 32bit:
```
$ arch
i686
$ rpm -q python2-numpy
python2-numpy-1.14.5-3.fc29.i686
$ python2
Python 2.7.15 (default, Jul 15 2018, 06:03:07) 
[GCC 8.1.1 20180626 (Red Hat 8.1.1-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.longdouble
<type 'numpy.float96'>
>>> np.double
<type 'numpy.float64'>
>>> 
```
but they're the same on ARM 32bit:
```
$ arch
armv7l
$ rpm -q python2-numpy
python2-numpy-1.14.5-3.fc29.armv7hl
$ python2
Python 2.7.15 (default, Jul 15 2018, 05:48:59) 
[GCC 8.1.1 20180626 (Red Hat 8.1.1-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.longdouble
<type 'numpy.float64'>
>>> np.double    
<type 'numpy.float64'>
>>> 
```

I'm not sure if this means it's a bug in numpy or the test is making some unwarranted assumption.

**Comment by orbeckst** [comment]
Thanks for looking into the two architectures. I have access to neither – any suggestions are welcome.

**Comment by rathann** [comment]
Fedora has ARM (and other) machines available for packagers. I'm sure we can arrange for you to get access as an upstream developer. Could you join the #fedora-arm channel on Freenode IRC network and ask? Alternatively, ask on the arm mailing list (https://lists.fedoraproject.org/admin/lists/arm@lists.fedoraproject.org/).

**Comment by rathann** [comment]
I can confirm that tests are now passing on ARM 32bit with https://github.com/MDAnalysis/GridDataFormats/commit/3f2ca3bbeca9f828680d0e42bf2b21fae5f4de20 .

**Comment by orbeckst** [comment]
Thank you for testing!
